insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Dr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Ms');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Honorable');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Mrs');
insert into COURSE (title) values ('Mr');
insert into COURSE (title) values ('Rev');
insert into COURSE (title) values ('Ms');


insert into COURSE_MATERIAL (url, course_id) values ('http://acquirethisname.com/ut/suscipit/a/feugiat/et.png', 1);
insert into COURSE_MATERIAL (url, course_id) values ('https://shutterfly.com/quis/augue/luctus.jsp', 2);
insert into COURSE_MATERIAL (url, course_id) values ('http://toplist.cz/sed/sagittis/nam/congue/risus.html', 3);
insert into COURSE_MATERIAL (url, course_id) values ('https://about.com/vestibulum/ante.jsp', 4);
insert into COURSE_MATERIAL (url, course_id) values ('http://mapy.cz/potenti/in/eleifend/quam.jpg', 5);
insert into COURSE_MATERIAL (url, course_id) values ('http://dell.com/convallis.js', 6);
insert into COURSE_MATERIAL (url, course_id) values ('http://wikispaces.com/in.jsp', 7);
insert into COURSE_MATERIAL (url, course_id) values ('http://archive.org/ut/mauris/eget/massa/tempor/convallis.aspx', 8);
insert into COURSE_MATERIAL (url, course_id) values ('https://dyndns.org/faucibus/orci/luctus.aspx', 9);
insert into COURSE_MATERIAL (url, course_id) values ('http://pcworld.com/vestibulum/ante/ipsum/primis.html', 10);
insert into COURSE_MATERIAL (url, course_id) values ('https://1und1.de/integer/non/velit/donec/diam/neque/vestibulum.json', 11);
insert into COURSE_MATERIAL (url, course_id) values ('http://mashable.com/erat/nulla/tempus/vivamus/in/felis.aspx', 12);
insert into COURSE_MATERIAL (url, course_id) values ('https://icq.com/consectetuer/adipiscing/elit/proin/interdum.jpg', 13);
insert into COURSE_MATERIAL (url, course_id) values ('http://php.net/quam/turpis.aspx', 14);
insert into COURSE_MATERIAL (url, course_id) values ('http://npr.org/lorem/id/ligula/suspendisse/ornare/consequat/lectus.png', 15);
insert into COURSE_MATERIAL (url, course_id) values ('http://google.de/aliquet/ultrices/erat.html', 16);
insert into COURSE_MATERIAL (url, course_id) values ('http://parallels.com/vestibulum.jpg', 17);
insert into COURSE_MATERIAL (url, course_id) values ('http://discovery.com/ut/at.js', 18);
insert into COURSE_MATERIAL (url, course_id) values ('http://upenn.edu/luctus/et/ultrices/posuere.js', 19);
insert into COURSE_MATERIAL (url, course_id) values ('https://spotify.com/tempus/sit/amet/sem/fusce/consequat/nulla.aspx', 20);
insert into COURSE_MATERIAL (url, course_id) values ('http://chron.com/nam/nulla.aspx', 21);
insert into COURSE_MATERIAL (url, course_id) values ('https://seattletimes.com/mauris/non/ligula.jsp', 22);
insert into COURSE_MATERIAL (url, course_id) values ('http://blogger.com/odio/in/hac/habitasse/platea/dictumst/maecenas.json', 23);
insert into COURSE_MATERIAL (url, course_id) values ('https://unesco.org/interdum/in/ante.jpg', 24);
insert into COURSE_MATERIAL (url, course_id) values ('https://nature.com/phasellus/sit/amet/erat/nulla/tempus.json', 25);
insert into COURSE_MATERIAL (url, course_id) values ('https://joomla.org/vel/lectus/in/quam/fringilla/rhoncus/mauris.png', 26);
insert into COURSE_MATERIAL (url, course_id) values ('http://illinois.edu/varius.jsp', 27);
insert into COURSE_MATERIAL (url, course_id) values ('https://blogspot.com/morbi/non/lectus/aliquam/sit/amet/diam.json', 28);
insert into COURSE_MATERIAL (url, course_id) values ('http://goo.ne.jp/nisi/nam/ultrices/libero/non/mattis/pulvinar.jpg', 29);
insert into COURSE_MATERIAL (url, course_id) values ('http://mapy.cz/velit/id/pretium/iaculis/diam/erat/fermentum.jsp', 30);

